name: 'test-workflow'

on:
  workflow_call:
    inputs:
      run-test-job:
        required: true
        type: boolean

jobs:
  test-job:
    if: ${{ inputs.run-test-job }}
    runs-on: ubuntu-20.04
    steps:

      - name: 'test-step'
        run: echo "step was executed"
        shell: bash -ex {0}
